version: '3'

services:
  database:
    image: 'postgres:latest'
    container_name: IncludoLandPostgresDatabase
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: includo_land
