spring:
  application:
    name: includoland
  messages:
    basename: messages/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  datasource:
    url: jdbc:postgresql://localhost:5432/includoland
    username: includoland
    password: includoland
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-init.yaml
  cloud:
    r2:
      endpoint: ${R2_ENDPOINT}
      access-key: ${R2_ACCESS_KEY}
      secret-key: ${R2_SECRET_KEY}
      bucket-name: ${R2_BUCKET_NAME}
      public-url: ${R2_PUBLIC_URL}